In [53]:
import pandas as pd
import numpy as np 
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import cosine_similarity

In [25]:
df = pd.read_csv("missing_imputeted_df.csv")
df.head()

,colony,property_type,price_outer,price_per_sqft,Total Floors,Property Age,bedrooms,bathrooms,balconies,built_up_area,study room,servant room,store room,pooja room,others,view floor plan,furnishing_type,luxury_score,Overlooking_Categories
0,bhopal,House,105.0,3750,1.0,Old Property,7,5,0,2800.0,0,0,0,0,0,0,1,71,Green View Homes
1,kolar road,Flat,85.0,6508,2.0,New Property,3,3,1,1567.2,0,0,0,1,0,1,1,35,Green View Homes
2,katara hills,Flat,25.0,2173,3.0,New Property,2,2,3,957.0,0,0,0,0,0,0,1,15,Green View Homes
3,aishbagh,House,65.0,5909,2.0,Old Property,4,5,1,2400.0,0,0,0,1,0,0,0,18,Road Facing Homes
4,chuna bhatti,House,650.0,16250,3.0,New Property,6,6,2,4000.0,1,1,1,1,0,0,2,10,Road Facing Homes

In [26]:
# Price system
features_price = ['price_outer', 'property_type']
features_price

['price_outer', 'property_type']

In [27]:
# Area system
features_area = ['built_up_area', 'bedrooms', 'bathrooms', 'balconies']
features_area

['built_up_area', 'bedrooms', 'bathrooms', 'balconies']

In [28]:
features_facility = ['furnishing_type', 'Property Age']
features_facility

['furnishing_type', 'Property Age']

In [29]:
# # encode categoical variables
# df = pd.get_dummies(df, columns=['property_type','furnishing_type','Property Age'])
# df
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_data = scaler.fit_transform(df[numeric_cols])

In [51]:
t1 = df[features_price]
encoded = pd.get_dummies(t1,columns=['property_type'],dtype='int')
scaler = StandardScaler()
scaled = scaler.fit_transform(encoded)

In [56]:
sim1 = cosine_similarity(scaled,scaled)
sim1.shape

(1566, 1566)

In [ ]:
def recommend_properties(property_name, cosine_sim=cosine_sim):
    # Get the index of the property that matches the name
    idx = df.index[df['PropertyName'] == property_name].tolist()[0]

    # Get the pairwise similarity scores with that property
    sim_scores = list(enumerate(cosine_sim1[idx]))

    # Sort the properties based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the scores of the 10 most similar properties
    sim_scores = sim_scores[1:6]

    # Get the property indices
    property_indices = [i[0] for i in sim_scores]
    
    recommendations_df = pd.DataFrame({
        'PropertyName': df['PropertyName'].iloc[property_indices],
        'SimilarityScore': sim_scores
    })

    # Return the top 10 most similar properties
    return recommendations_df

In [82]:
# def recommend_properties(idx, cosine_sim=sim1):
l = [i[0] for i in sorted(list(enumerate(sim1[2])),key=lambda x : x[1],reverse=True)][1:10]
print(l)
df.iloc[l]

[52, 56, 115, 123, 132, 198, 234, 261, 322]

,colony,property_type,price_outer,price_per_sqft,Total Floors,Property Age,bedrooms,bathrooms,balconies,built_up_area,study room,servant room,store room,pooja room,others,view floor plan,furnishing_type,luxury_score,Overlooking_Categories
52,shahjahanabad,Flat,25.0,2617,4.0,New Property,4,4,1,1146.000000,0,0,0,0,0,0,0,73,Road Facing Homes
56,ayodhya bypass,Flat,25.0,5000,3.0,Moderate Property,1,1,1,388.685252,0,0,0,0,0,0,1,65,Road Facing Homes
115,katara hills,Flat,25.0,3846,2.0,Moderate Property,2,2,1,779.000000,0,0,0,0,0,0,0,82,Green View Homes
123,piplani,Flat,25.0,2777,3.0,Old Property,2,2,1,1080.000000,0,0,0,0,0,0,1,0,Road Facing Homes
132,mandideep,Flat,25.0,3333,1.0,New Property,2,2,1,900.000000,0,0,0,0,0,0,1,35,Amenity Facing Homes
198,chuna bhatti,Flat,25.0,2744,1.0,Old Property,2,2,3,1093.200000,0,0,0,0,0,0,1,0,Road Facing Homes
234,gehu kheda,Flat,25.0,3125,4.0,Moderate Property,2,2,0,621.896404,0,0,0,0,0,0,1,8,Road Facing Homes
261,katara hills,Flat,25.0,3333,3.0,Moderate Property,2,1,1,900.000000,0,0,0,0,0,0,2,14,Road Facing Homes
322,central bhopal,Flat,25.0,5000,1.0,Old Property,2,2,0,600.000000,0,0,0,0,0,0,1,0,Road Facing Homes

In [57]:
df.head()

,colony,property_type,price_outer,price_per_sqft,Total Floors,Property Age,bedrooms,bathrooms,balconies,built_up_area,study room,servant room,store room,pooja room,others,view floor plan,furnishing_type,luxury_score,Overlooking_Categories
0,bhopal,House,105.0,3750,1.0,Old Property,7,5,0,2800.0,0,0,0,0,0,0,1,71,Green View Homes
1,kolar road,Flat,85.0,6508,2.0,New Property,3,3,1,1567.2,0,0,0,1,0,1,1,35,Green View Homes
2,katara hills,Flat,25.0,2173,3.0,New Property,2,2,3,957.0,0,0,0,0,0,0,1,15,Green View Homes
3,aishbagh,House,65.0,5909,2.0,Old Property,4,5,1,2400.0,0,0,0,1,0,0,0,18,Road Facing Homes
4,chuna bhatti,House,650.0,16250,3.0,New Property,6,6,2,4000.0,1,1,1,1,0,0,2,10,Road Facing Homes

In [90]:
# area system
t1 = df[features_area]
st = StandardScaler()
scaled1 = st.fit_transform(t1)
scaled1.shape

(1566, 4)

In [92]:
sim2 = cosine_similarity(scaled1,scaled1)
sim2.shape

(1566, 1566)

In [95]:
l = [i[0] for i in sorted(list(enumerate(sim2[2])),key=lambda x : x[1],reverse=True)][1:10]
print(l)
df.iloc[l]

[1433, 1081, 248, 165, 1420, 285, 774, 1202, 155]

,colony,property_type,price_outer,price_per_sqft,Total Floors,Property Age,bedrooms,bathrooms,balconies,built_up_area,study room,servant room,store room,pooja room,others,view floor plan,furnishing_type,luxury_score,Overlooking_Categories
1433,katara hills,Flat,28.00,3544,6.0,New Property,2,2,3,948.000000,0,0,0,0,0,0,1,22,Green View Homes
1081,ayodhya bypass,Flat,27.50,2291,1.0,New Property,2,2,3,946.000000,0,0,0,0,0,0,1,25,Road Facing Homes
248,chuna bhatti,Flat,20.00,2167,1.0,Old Property,2,2,3,923.000000,0,0,0,0,0,0,1,0,Road Facing Homes
165,gandhinagar,Flat,35.00,2788,3.0,New Property,2,2,3,900.000000,0,0,0,0,0,0,1,105,Amenity Facing Homes
1420,hoshangabad road,Flat,26.00,3058,2.0,Moderate Property,2,2,3,895.000000,0,0,0,0,0,0,1,45,Amenity Facing Homes
285,central bhopal,Flat,65.00,4814,7.0,Old Property,2,2,3,1049.450181,0,0,0,0,0,1,0,66,Amenity Facing Homes
774,gandhinagar,Flat,30.00,4000,6.0,Moderate Property,2,2,3,862.000000,0,0,0,0,0,0,1,44,Green View Homes
1202,kolar road,Flat,22.99,2343,1.0,Moderate Property,2,2,3,831.000000,0,0,0,1,1,0,1,56,Green View Homes
155,gehu kheda,Flat,22.00,2242,5.0,New Property,2,2,3,825.000000,0,0,0,0,0,0,1,41,Amenity Facing Homes

In [99]:
t3 = df[features_facility]
encoded3 = pd.get_dummies(t3,columns=['Property Age'],dtype='int')
st3 = StandardScaler()
scaled3 = st3.fit_transform(encoded3)
scaled3.shape

(1566, 5)

In [100]:
sim3 = cosine_similarity(scaled3,scaled3)
sim3.shape

(1566, 1566)

In [101]:
l = [i[0] for i in sorted(list(enumerate(sim3[2])),key=lambda x : x[1],reverse=True)][1:10]
print(l)
df.iloc[l]

[2, 5, 7, 8, 17, 19, 22, 31, 33]

,colony,property_type,price_outer,price_per_sqft,Total Floors,Property Age,bedrooms,bathrooms,balconies,built_up_area,study room,servant room,store room,pooja room,others,view floor plan,furnishing_type,luxury_score,Overlooking_Categories
2,katara hills,Flat,25.0,2173,3.0,New Property,2,2,3,957.000000,0,0,0,0,0,0,1,15,Green View Homes
5,kolar road,House,75.0,4687,1.0,New Property,4,6,2,2400.000000,1,0,1,1,0,0,1,37,Road Facing Homes
7,misrod,House,71.0,9659,2.0,New Property,3,3,2,735.000000,0,0,0,0,0,0,1,31,Green View Homes
8,kolar road,House,145.0,5370,1.0,New Property,4,4,1,2700.000000,0,0,0,0,0,0,1,13,Road Facing Homes
17,salaiya,Flat,68.0,3885,5.0,New Property,3,3,2,1360.398383,0,0,0,0,0,0,1,67,Amenity Facing Homes
19,bhopal,House,40.0,7619,3.0,New Property,2,1,1,525.000000,0,0,0,0,0,0,1,22,Road Facing Homes
22,hoshangabad road,House,260.0,18571,4.0,New Property,4,5,1,1400.000000,0,1,0,1,1,0,1,22,Amenity Facing Homes
31,gandhinagar,House,85.0,5666,1.0,New Property,3,4,2,1000.000000,0,0,0,0,0,0,1,25,Green View Homes
33,outside bhopal,House,55.0,6111,2.0,New Property,4,2,2,2160.000000,0,0,0,0,1,0,1,3,Green View Homes

In [108]:
def recommend_properties(idx, sim1=sim1,sim2=sim2,sim3=sim3):
    # Get the index of the property that matches the name
    # idx = df.index[df['PropertyName'] == property_name].tolist()[0]/

    # combine similarity
    price_w = 0.9
    area_w = 0.6
    facility_w = 0.3

    combine_similarity = price_w*sim1 + area_w*sim2 + facility_w*sim3

    # Get the pairwise similarity scores with that property
    sim_scores = list(enumerate(combine_similarity[idx]))

    # Sort the properties based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the scores of the 10 most similar properties
    sim_scores = sim_scores[1:6]

    # Get the property indices
    property_indices = [i[0] for i in sim_scores]
    
    recommendations_df = df.iloc[property_indices]

    # Return the top 10 most similar properties
    return recommendations_df

In [110]:
recommend_properties(4)

,colony,property_type,price_outer,price_per_sqft,Total Floors,Property Age,bedrooms,bathrooms,balconies,built_up_area,study room,servant room,store room,pooja room,others,view floor plan,furnishing_type,luxury_score,Overlooking_Categories
384,hoshangabad road,House,500.0,13513,3.0,New Property,6,7,3,5500.0,1,1,0,1,1,0,2,116,Green View Homes
1476,arera colony,House,1550.0,34444,2.0,New Property,10,9,2,4500.0,1,1,1,1,0,0,2,118,Green View Homes
244,chuna bhatti,House,670.0,16750,2.0,New Property,6,6,3,8700.0,1,1,1,1,0,0,2,80,Amenity Facing Homes
782,chuna bhatti,House,545.0,5450,4.0,New Property,7,7,3,12000.0,1,1,1,1,0,0,2,137,Green View Homes
504,bagmugaliya,House,325.0,13541,2.0,New Property,5,5,3,4800.0,1,0,0,1,1,0,2,14,Green View Homes

In [106]:
df.head()

,colony,property_type,price_outer,price_per_sqft,Total Floors,Property Age,bedrooms,bathrooms,balconies,built_up_area,study room,servant room,store room,pooja room,others,view floor plan,furnishing_type,luxury_score,Overlooking_Categories
0,bhopal,House,105.0,3750,1.0,Old Property,7,5,0,2800.0,0,0,0,0,0,0,1,71,Green View Homes
1,kolar road,Flat,85.0,6508,2.0,New Property,3,3,1,1567.2,0,0,0,1,0,1,1,35,Green View Homes
2,katara hills,Flat,25.0,2173,3.0,New Property,2,2,3,957.0,0,0,0,0,0,0,1,15,Green View Homes
3,aishbagh,House,65.0,5909,2.0,Old Property,4,5,1,2400.0,0,0,0,1,0,0,0,18,Road Facing Homes
4,chuna bhatti,House,650.0,16250,3.0,New Property,6,6,2,4000.0,1,1,1,1,0,0,2,10,Road Facing Homes

In [111]:
import joblib
joblib.dump(sim1,'price_sim.joblib')

['price_sim.joblib']

In [113]:
joblib.dump(sim2,'area_sim.joblib')

['area_sim.joblib']

In [114]:
joblib.dump(sim3,'facility_sim.joblib')

['facility_sim.joblib']